version: "3"
services:
  spark-job-service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./Local_data:/app/Local_Data/Product
      - ./Delta_Table:/app/Delta_Table
    environment:
      - SPARK_MASTER=local[*]

  spark-history-server:
    image: rangareddy1988/spark-history-server:${VERSION:-latest}
    container_name: spark-history-server
    command:
      - "/sbin/tini"
      - "-s"
      - "--"
      - "/opt/spark/bin/spark-class"
      - "-Dspark.history.fs.logDirectory=/app/spark_history_logs"
      - "org.apache.spark.deploy.history.HistoryServer"
    volumes:
      - ./spark_history_logs:/app/spark_history_logs
